gui/views/car.py
from flask import Blueprint, render_template, session, redirect, url_for, \
     request, flash, g, jsonify, abort
from gui.utils import do_get_paginated_cars, do_get_car, do_add_car, do_return_car,do_logout,do_get_paginated_fix,do_get_user_tok
import json

mod = Blueprint('cars', __name__)


@mod.route('/cars/')
def index():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    return render_template("/cars/index.html")


@mod.route('/cars/get', methods=['GET', 'POST'])
def get():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        return render_template("/cars/get.html", ticket_found = False)
    else:
        if 'car_id' not in request.form or request.form['car_id'] == '':
            flash('Идентификатор не задан', "error")
            return redirect(url_for('cars.get'))
        else:
            car_id = request.form["car_id"]
            result = do_get_car(car_id,request.cookies)

            if result.success:
                if result.response.status_code == 200:
                    car = json.loads(result.response.content)
                    return render_template("/cars/get.html", car=car, car_found=True)
                else:
                    flash("Машину не найден", "error")
                    return redirect(url_for('cars.get'))
            else:
                flash(result.error, "error")
                return redirect(url_for('cars.get'))


@mod.route('/cars/add', methods=['GET', 'POST'])
def add():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        result = do_get_paginated_fix(1, 100, request.cookies)
        if result.success:
            if result.response.status_code == 200:
                fixes_obj = result.response.content
                fixes_str = (str(fixes_obj)).split('\\n')
                n = len(fixes_str)
                fixes_str[0] = fixes_str[0][2:]
                fixes_str[n - 1] = fixes_str[n - 1][0:-1]
                fixes = []
                fixes_str.remove(fixes_str[n - 1])
                for fix in fixes_str:
                    if fix != "":
                        fixl = json.loads(bytes(fix, 'utf8'))
                        ar = fixl["car_ids"]
                        ar1 = fixl["meh_ids"]
                        number_of_mehs = len(ar1)
                        number_of_cars = len(ar)
                        datetime = str(fixl["datetime"])
                        dictionary = {"fix_id": fixl["fix_id"], "number_of_mehs": number_of_mehs,
                                      "number_of_cars": number_of_cars,
                                      "date_time": datetime}
                        fixes.append(dictionary)
            #user_id=request.args['user_id']
            return render_template("/cars/add.html", fixes=fixes)
    else:
        fix_id = request.form['fix_id']
        name = request.form['name']
        result = do_add_car(fix_id, name, request.cookies)
        #flash(request.cookies, 'info')
        if result.success:
            #flash(result.response.status_code, 'info')
            if result.response.status_code == 201:
                flash('Запрос на починку успешно добавлен', 'info')
                return redirect(url_for('cars.get_all'))
            elif result.response.status_code == 403:
                do_logout()
                return redirect(url_for('users.login'))
            else:
                flash('Запрос на починку не может быть добавлен', 'error')
                return redirect(url_for('cars.get_all'))
        else:
            flash(result.error, 'error')
            return redirect(url_for('cars.get_all'))




@mod.route('/cars/ret' ,methods=['GET', 'POST'])
def ret():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        car_id = request.args['car_id']
        return render_template("/cars/ret.html", car_id=car_id)
    else:
        if request.form['submit'] == 'Нет':
            return redirect(url_for('mehs.get_all'))

        if request.form['submit'] == 'Да':
            car_id =request.args['car_id']
            result = do_return_car(car_id, request.cookies)
            if result.success:
                if result.response.status_code == 204:
                    flash('Возврат машины успешно произведен', 'info')
                    return redirect(url_for('menu.index'))
                elif result.response.status_code == 403:
                    do_logout()
                    return redirect(url_for('users.login'))
                else:
                    flash('Возврат машины не может быть произведен', 'error')
                    return redirect(url_for('menu.index'))
            else:
                flash(result.error, 'error')
            return redirect(url_for('menu.index'))


@mod.route('/cars/get_all')
def get_all():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        if 'page' not in request.args:
            return redirect(url_for('cars.get_all', page=1))
        page = request.args.get('page', 1, type=int)
        result = do_get_paginated_cars(page, 10,request.cookies)
        if result.success:
            if result.response.status_code == 200:
                cars_obj = result.response.content
                cars_str = (str(cars_obj)).split('\\n')
                n = len(cars_str)
                cars_str[0] = cars_str[0][2:]
                cars_str[n-1] = cars_str[n-1][0:-1]
                cars = []
                dictr = json.loads(cars_str[n-1])
                cars_str.remove(cars_str[n-1])
                for car in cars_str:
                    if car != '':
                        carl = bytes(car, 'utf8')
                        cars.append(json.loads(carl))
                return render_template("/cars/get_all.html", cars=cars, prev_url=dictr['is_prev_page'],
                                       next_url=dictr['is_next_page'], next_page=page+1, prev_page=page-1)
            else:
                flash("Машины не найдены", "error")
                return redirect(url_for('cars.index'))
        else:
            flash(result.error, "error")
            return redirect(url_for('cars.index'))

@mod.route('/cars/get1', methods=['GET', 'POST'])
def get1():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        if 'car_id' not in request.args:
            flash('Идентификатор не задан', "error")
            return redirect(url_for('cars.get'))
        else:
            car_id = request.args.get('car_id', 1, type=str)
            result = do_get_car(car_id,request.cookies)

            if result.success:
                if result.response.status_code == 200:
                    car = json.loads(result.response.content)
                    result=do_get_user_tok(request.cookies)
                    user=json.loads(result.response.content)
                    return render_template("/cars/get1.html", car=car, car_found=True, admin=user['admin'])
                else:
                    flash("Мащина не найдена", "error")
                    return redirect(url_for('cars.get'))
            else:
                flash(result.error, "error")
                return redirect(url_for('cars.get'))

gui/views/fix.py
from flask import Blueprint, render_template, session, redirect, url_for, \
     request, flash, g, jsonify, abort
from gui.utils import do_create_fix, do_get_paginated_fix, do_get_fix , do_rem_meh
import json

mod = Blueprint('fixes', __name__)


@mod.route('/fixes/')
def index():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    flag = request.args['flag']
    return render_template("/fixes/index.html",flag=flag)


@mod.route('/fixes/get/<fix_id>', methods=['GET', 'POST'])
def get(fix_id):
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        result = do_get_fix(fix_id,request.cookies)
        if result.success:
            if result.response.status_code == 200:
                tmp = str(result.response.content)
                list_sm = tmp.split('\\n')
                fix = list_sm[0]
                fix = fix[2:]
                fix_d = json.loads(fix)
                datetime = str(fix_d["datetime"])
                ar = fix_d["car_ids"]
                md=fix_d["meh_ids"]
                dictionaryf={"fix_id": fix_d["fix_id"], "meh_ids": md, "car_ids": ar,"date_time":datetime}
                n = len(list_sm)
                list_sm[0] = list_sm[0][2:]
                list_sm[n-1] = list_sm[n-1][0:-1]
                mehs = []
                list_sm.remove(list_sm[0])

                for meh in list_sm:
                    if meh != "" :
                        mehl = json.loads(bytes(meh, 'utf8'))
                        #ar = mehl["meh_id"]
                        dictionarym = {"meh_id": mehl["meh_id"], "name": mehl["name"],
                                      "lvl": mehl["lvl"],
                                      "year": mehl["year"]}
                        mehs.append(dictionarym)

                #meh_d = json.loads(meh)
                return render_template("/fixes/get.html", fix=dictionaryf, mehs=mehs, number_of_cars= len(ar)+1,cars=ar)
            else:
                flash('Ошибка. Мастерской не существует.', "error")
                return redirect(url_for('fixes.get_all'), "error")
        else:
            flash(result.error, "error")
            return redirect(url_for('fixes.get_all'), "error")


@mod.route('/fixes/create', methods=['GET', 'POST'])
def create():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
            return render_template("/fixes/create.html")
    else:
        failed = False
        if 'date_time' not in request.form or request.form['date_time']=='':
            flash('Дата создания не задана', "error")
            failed = True
        if failed:
            return render_template("/fixes/create.html")

        result = do_create_fix( request.form['date_time'],request.cookies)
        if result.success:
            if result.response.status_code == 201:
                flash('Сеанс успешно создан', "info")
                response = redirect('fixes/get_all')
                return response
            else:
                st = result.response.content.decode('utf-8')
                if st=='':
                    st = str(result.response.content)
                flash(st, "error")
                return redirect(url_for('fixes/get_all'))
        else:
            flash(result.error)
            return redirect(url_for('fixes/get_all'), "error")


@mod.route('/fixes/get_all')
def get_all():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        if 'page' not in request.args:
            return redirect(url_for('fixes.get_all', page=1))
        page = request.args.get('page', 1, type=int)
        result = do_get_paginated_fix(page, 10,request.cookies)
        if result.success:
            if result.response.status_code == 200:
                fixes_obj = result.response.content
                fixes_str = (str(fixes_obj)).split('\\n')
                n = len(fixes_str)
                fixes_str[0] = fixes_str[0][2:]
                fixes_str[n-1] = fixes_str[n-1][0:-1]
                fixes = []
                dictr = json.loads(fixes_str[n-1])
                fixes_str.remove(fixes_str[n-1])
                for fix in fixes_str:
                    if fix != "":
                        fixl = json.loads(bytes(fix, 'utf8'))
                        ar = fixl["car_ids"]
                        ar1 = fixl["meh_ids"]
                        number_of_mehs = len(ar1)
                        number_of_cars = len(ar)
                        datetime = str(fixl["datetime"])
                        dictionary = {"fix_id": fixl["fix_id"], "number_of_mehs": number_of_mehs,
                                      "number_of_cars": number_of_cars,
                                      "date_time":datetime}
                        fixes.append(dictionary)
                return render_template("/fixes/get_all.html", fixes=fixes, prev_url=dictr['is_prev_page'],
                                       next_url=dictr['is_next_page'], next_page=page+1, prev_page=page-1)
            else:
                flash("Мастерские не найдены", "error")
                return redirect(url_for('fixes.index', flag='FALSE'))
        else:
            flash(result.error, "error")
            return redirect(url_for('fixes.index', flag='FALSE'))


@mod.route('/fixes/patchrem', methods=['GET', 'POST'])
def patchrem():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        fix_id = request.args['fix_id']
        meh_id = request.args['meh_id']
        return render_template("/fixes/patchrem.html",fix_id = fix_id, meh_id = meh_id)
    else:
        if 'meh_id' not in request.args or request.args['meh_id'] == '':
            flash('Идентификатор не задан', "error")
            return redirect(url_for('fixes.get',fix_id=request.args['fix_id']))
        else:
            fix_id = request.args['fix_id']
            meh_id = request.args['meh_id']
            result = do_rem_meh(fix_id, meh_id, "mehrem",request.cookies)

            if result.success:
                if result.response.status_code == 201:
                    flash("Механик уволен", "info")

                    return render_template("/fixes/get_all.html")
                else:
                    flash("Механик не уволен", "error")
                    return redirect(url_for('fixes.get_all'))
            else:
                flash(result.error, "error")
                return redirect(url_for('fixes.get_all'))

gui/templates/fixes/create.html
{% extends "layout.html" %}
{% block title %}Добавить мастерскую{% endblock %}
{% block body %}
  <form action="" method=post>
    <p>
    <input type=text placeholder="Дата создания" name=date_time value="{{ request.form.date_time }}">
    <p>

    <input type=submit value=Ok>
    <p>
  </form>
{% endblock %}

gui/templates/fixes/get.html
{% extends "layout.html" %}
{% block title %}Информация о мастерской{% endblock %}
{% block body %}
    <form action="" method="post">

    <h3>Мастерская</h3>
            <table>
            <tr>
                <th> Идентификатор </th>
                <td> {{ fix["fix_id"] }}</td>
            </tr>
            <tr>
                <th> Дата открытия </th>
                <td> {{ fix["date_time"] }}</td>
            </tr>
            </table>
    <h3>Машины</h3>
                {% for i in range(number_of_cars) %}
                    {% if i>0 %}
                        {% if cars[i-1] %}
                            <input type=hidden name="car_id" value="{{ cars[i] }}"/>
                            <a style="text-decoration-color: #00FF00" href="{{ url_for('cars.get1', car_id=cars[i-1]) }}">{{ cars[i-1] }}</a>
                        {% endif %}
                    {% endif %}
                {% endfor %}
    <h3>Механики</h3>
                {% for item in mehs %}
                <table>
                <tr>
                    <th> Идентификатор </th>
                    <td> {{ item["meh_id"] }}</td>
                </tr>
                <tr>
                    <th> Имя </th>
                    <td> {{ item["name"] }}</td>
                </tr>
                <tr>
                    <th> Стаж </th>
                    <td> {{ item["lvl"] }}</td>
                </tr>
                <tr>
                    <th> Год рождения </th>
                    <td> {{ item["year"] }}</td>
                </tr>
                </table>
          <a href="{{ url_for('fixes.patchrem',fix_id=fix["fix_id"], meh_id=item["meh_id"] )}}">Уволить механика</a>
    {% endfor %}

    </form>

{% endblock %}

gui/templates/fixes/get_all.html
{% extends "layout.html" %}
{% block title %}Информация о мастерских{% endblock %}
{% block body %}
    <form action="" method="get">
            {% for item in fixes %}
                <table>
                <tr>
                    <th> Идентификатор </th>
                    <td> {{ item["fix_id"] }}</td>
                </tr>
                <tr>
                    <th> Кол-во механиков </th>
                    <td> {{ item["number_of_mehs"] }}</td>
                </tr>
                <tr>
                    <th> Общее количество машин </th>
                    <td> {{ item["number_of_cars"] }}</td>
                </tr>
                <tr>
                    <th> Дата создания </th>
                    <td> {{ item["date_time"] }}</td>
                </tr>
                </table>
                <a href="{{ url_for('fixes.get', fix_id=item["fix_id"]) }}">Посмотреть мастерскую</a>
            {% endfor %}
            <p></p>
            {% if prev_url %}
                <a href="{{ url_for('fixes.get_all', page=prev_page) }}">Предыдущие сеансы</a>
            {% endif %}
            {% if next_url %}
                <a href="{{ url_for('fixes.get_all', page=next_page) }}" >Следующие сеансы</a>
            {% endif %}
    </form>
{% endblock %}

gui/templates/fixes/index.html
{% extends "layout.html" %}
{% block body %}
<title>{% block title %}Мастерские{% endblock %}</title>
    <p class=nav>
    <a href="{{ url_for('fixes.get_all') }}">Посмотреть список всех мастерских</a>
    <p class=nav>
    {% if flag == 'True' %}
    <a href="{{ url_for('fixes.create') }}">Создать мастерскую</a>
    {% endif %}
{% endblock %}

gui/templates/fixes/patchrem.html
{% extends "layout.html" %}
{% block title %}Уволить механика{% endblock %}
{% block body %}
  <form action="" method=post>
    <p>
      <h4 >Идентификатор мастерской: {{ fix_id }}</h4>

    <p>
      {% if meh_id!='' %}
            <h4 >Идентификатор мастерской: <input type=text placeholder="Идентификатор механика" name=meh_id value="{{ meh_id }}"></h4>


      {% else  %}
            <h4 >Идентификатор мастерской: <input type=text placeholder="Идентификатор механика" name=meh_id value="{{ request.form.meh_id }}"></h4>
      {% endif %}
      <p>


    <input type=submit value=Ok>
    <p>
  </form>
{% endblock %}