gui/views/car.py
from flask import Blueprint, render_template, session, redirect, url_for, \
     request, flash, g, jsonify, abort
from gui.utils import do_get_paginated_cars, do_get_car, do_add_car, do_return_car,do_logout,do_get_paginated_fix,do_get_user_tok
import json

mod = Blueprint('cars', __name__)


@mod.route('/cars/')
def index():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    return render_template("/cars/index.html")


@mod.route('/cars/get', methods=['GET', 'POST'])
def get():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        return render_template("/cars/get.html", ticket_found = False)
    else:
        if 'car_id' not in request.form or request.form['car_id'] == '':
            flash('Идентификатор не задан', "error")
            return redirect(url_for('cars.get'))
        else:
            car_id = request.form["car_id"]
            result = do_get_car(car_id,request.cookies)

            if result.success:
                if result.response.status_code == 200:
                    car = json.loads(result.response.content)
                    return render_template("/cars/get.html", car=car, car_found=True)
                else:
                    flash("Машину не найден", "error")
                    return redirect(url_for('cars.get'))
            else:
                flash(result.error, "error")
                return redirect(url_for('cars.get'))


@mod.route('/cars/add', methods=['GET', 'POST'])
def add():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        result = do_get_paginated_fix(1, 100, request.cookies)
        if result.success:
            if result.response.status_code == 200:
                fixes_obj = result.response.content
                fixes_str = (str(fixes_obj)).split('\\n')
                n = len(fixes_str)
                fixes_str[0] = fixes_str[0][2:]
                fixes_str[n - 1] = fixes_str[n - 1][0:-1]
                fixes = []
                fixes_str.remove(fixes_str[n - 1])
                for fix in fixes_str:
                    if fix != "":
                        fixl = json.loads(bytes(fix, 'utf8'))
                        ar = fixl["car_ids"]
                        ar1 = fixl["meh_ids"]
                        number_of_mehs = len(ar1)
                        number_of_cars = len(ar)
                        datetime = str(fixl["datetime"])
                        dictionary = {"fix_id": fixl["fix_id"], "number_of_mehs": number_of_mehs,
                                      "number_of_cars": number_of_cars,
                                      "date_time": datetime}
                        fixes.append(dictionary)
            #user_id=request.args['user_id']
            return render_template("/cars/add.html", fixes=fixes)
    else:
        fix_id = request.form['fix_id']
        name = request.form['name']
        result = do_add_car(fix_id, name, request.cookies)
        #flash(request.cookies, 'info')
        if result.success:
            #flash(result.response.status_code, 'info')
            if result.response.status_code == 201:
                flash('Запрос на починку успешно добавлен', 'info')
                return redirect(url_for('cars.get_all'))
            elif result.response.status_code == 403:
                do_logout()
                return redirect(url_for('users.login'))
            else:
                flash('Запрос на починку не может быть добавлен', 'error')
                return redirect(url_for('cars.get_all'))
        else:
            flash(result.error, 'error')
            return redirect(url_for('cars.get_all'))




@mod.route('/cars/ret' ,methods=['GET', 'POST'])
def ret():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        car_id = request.args['car_id']
        return render_template("/cars/ret.html", car_id=car_id)
    else:
        if request.form['submit'] == 'Нет':
            return redirect(url_for('mehs.get_all'))

        if request.form['submit'] == 'Да':
            car_id =request.args['car_id']
            result = do_return_car(car_id, request.cookies)
            if result.success:
                if result.response.status_code == 204:
                    flash('Возврат машины успешно произведен', 'info')
                    return redirect(url_for('menu.index'))
                elif result.response.status_code == 403:
                    do_logout()
                    return redirect(url_for('users.login'))
                else:
                    flash('Возврат машины не может быть произведен', 'error')
                    return redirect(url_for('menu.index'))
            else:
                flash(result.error, 'error')
            return redirect(url_for('menu.index'))


@mod.route('/cars/get_all')
def get_all():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        if 'page' not in request.args:
            return redirect(url_for('cars.get_all', page=1))
        page = request.args.get('page', 1, type=int)
        result = do_get_paginated_cars(page, 10,request.cookies)
        if result.success:
            if result.response.status_code == 200:
                cars_obj = result.response.content
                cars_str = (str(cars_obj)).split('\\n')
                n = len(cars_str)
                cars_str[0] = cars_str[0][2:]
                cars_str[n-1] = cars_str[n-1][0:-1]
                cars = []
                dictr = json.loads(cars_str[n-1])
                cars_str.remove(cars_str[n-1])
                for car in cars_str:
                    if car != '':
                        carl = bytes(car, 'utf8')
                        cars.append(json.loads(carl))
                return render_template("/cars/get_all.html", cars=cars, prev_url=dictr['is_prev_page'],
                                       next_url=dictr['is_next_page'], next_page=page+1, prev_page=page-1)
            else:
                flash("Машины не найдены", "error")
                return redirect(url_for('cars.index'))
        else:
            flash(result.error, "error")
            return redirect(url_for('cars.index'))

@mod.route('/cars/get1', methods=['GET', 'POST'])
def get1():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        if 'car_id' not in request.args:
            flash('Идентификатор не задан', "error")
            return redirect(url_for('cars.get'))
        else:
            car_id = request.args.get('car_id', 1, type=str)
            result = do_get_car(car_id,request.cookies)

            if result.success:
                if result.response.status_code == 200:
                    car = json.loads(result.response.content)
                    result=do_get_user_tok(request.cookies)
                    user=json.loads(result.response.content)
                    return render_template("/cars/get1.html", car=car, car_found=True, admin=user['admin'])
                else:
                    flash("Мащина не найдена", "error")
                    return redirect(url_for('cars.get'))
            else:
                flash(result.error, "error")
                return redirect(url_for('cars.get'))

gui/views/user.py
from flask import Blueprint, render_template, session, redirect, url_for, \
     request, flash, g, jsonify, abort
from gui.utils import do_get_paginated_user, do_get_user, do_authorization,\
    do_logout,do_get_code,do_get_user_tok,do_get_auth_token,do_create_user
import json

mod = Blueprint('users', __name__)


@mod.route('/users/')
def index():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    flag = request.args['flag']
    return render_template("/users/index.html",flag=flag)

@mod.route('/APIlogin1')
def APIlogin1():
    client_id = 1
    client_secret = 123
    result = do_get_code(client_id)
    if result.success:
        if result.response.status_code == 201:
            code_d = json.loads(result.response.content)
            code = code_d['code']
            response = redirect(url_for('users.APIlogin2', code=code, client_id=client_id, client_secret=client_secret))
            return response
        else:
            flash(result.response.content.decode('utf-8'), 'error')
            return redirect(url_for('users.login'))
    else:
        flash(result.error)
    return redirect(url_for('users.login'))


@mod.route('/APIlogin2')
def APIlogin2():
    client_id = request.args.get('client_id', type=int)
    client_secret = request.args.get('client_secret', type=int)
    code = request.args.get('code', type=str)
    result = do_get_auth_token(client_id, client_secret, code)

    if result.success:
        flash(result.response.status_code, 'info')
        if result.response.status_code == 200:
            response = redirect(url_for('menu.index'))
            response.headers["Set-Cookie"] = result.response.headers["Set-Cookie"]
            g.user = result.response.cookies
            return response
        else:
            flash(result.response.content.decode('utf-8'))
            return redirect(url_for('users.login'))
    else:
        flash(result.error)
    return redirect(url_for('users.login'))
@mod.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("/users/login.html")
    else:
        fail = False
        if 'l_name' not in request.form or request.form['l_name'] == '':
            flash('Логин не задан', "error")
            fail = True
        if 'password' not in request.form or request.form['password'] == '':
            flash('Пароль не задан', "error")
            fail = True
        if fail:
            return redirect(url_for('users.login'))
        l_name = request.form['l_name']
        password = request.form['password']
        result = do_authorization(l_name, password)
        if result.success:
            if result.response.status_code == 200:
                response = redirect(url_for('menu.index'))

                response.headers["Set-Cookie"] = result.response.headers["Set-Cookie"]
                #flash(result.response.cookies, 'info')
                g.user = result.response.cookies
                #g.logged_in = True
                return response

            else:
                flash(result.response.content.decode('utf-8'))
                return redirect(url_for('users.login'))
        else:
            flash(result.error)
        return redirect(url_for('users.login'))


@mod.route('/users/logout')
def logout():
    result = do_logout()
    response = redirect(url_for(result.redirect))
    response.delete_cookie('token')
    return response


@mod.route('/users/get/<user_id>')
def get(user_id):
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        result = do_get_user(user_id,request.cookies)
        if result.success:
            if result.response.status_code == 200:
                user = json.loads(result.response.content)
                return render_template("/users/get.html", user = user)
            else:
                flash('Юзер не найде существует.', "error")
                return redirect(url_for('users.get_all'), "error")
        else:
            flash(result.error, "error")
            return redirect(url_for('users.get_all'), "error")

@mod.route('/users/get1/')
def get1():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        result = do_get_user_tok(request.cookies)
        if result.success:
            if result.response.status_code == 200:
                user = json.loads(result.response.content)
                flag=user['status']
                return render_template("/users/get1.html", user = user,flag=flag)
            else:
                flash('Ошибка Юзер Не найден перезайди', "error")
                return redirect(url_for('users.get_all'), "error")
        else:
            flash(result.error, "error")
            return redirect(url_for('users.get_all'), "error")


@mod.route('/users/get_all')
def get_all():
    if not g.logged_in:
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        if 'page' not in request.args:
            return redirect(url_for('users.get_all', page=1))
        page = request.args.get('page', 1, type=int)
        result = do_get_paginated_user(page, 10,request.cookies)
        if result.success:
            if result.response.status_code == 200:
                users_obj = result.response.content
                users_str = (str(users_obj)).split('\\n')
                n = len(users_str)
                users_str[0] = users_str[0][2:]
                users = []
                users_str[n-1] = users_str[n-1][0:-1]
                dictr = json.loads(users_str[n-1])
                users_str.remove(users_str[n-1])
                for user in users_str:
                    if user != "":
                        user1 = bytes(user, 'utf8')
                        users.append(json.loads(user1))
                return render_template("/users/get_all.html", users=users, prev_url=dictr['is_prev_page'],
                                       next_url=dictr['is_next_page'], next_page=page+1, prev_page=page-1)
            else:
                flash("Потльзователь не найден", "error")
                return redirect(url_for('menu.index'))
        else:
            flash(result.error, "error")
            return redirect(url_for('menu.index'))

@mod.route('/create', methods=['GET', 'POST'])
def create():
    flag = 1
    if not g.logged_in:
        flag = 0
    if request.method == 'GET':
            if flag == 1:
                result = do_get_user_tok(request.cookies)
                if result.success:
                    if result.response.status_code == 200:
                        user = json.loads(result.response.content)
                        if user['admin']!= 'True':
                            flag = 0
            return render_template("/users/create.html", flag=flag)
    else:
        failed = False
        if 'l_name' not in request.form or request.form['l_name']=='':
            flash('Логин не задана', "error")
            failed = True
        if 'password' not in request.form or request.form['password']=='':
            flash('Пароль не задана', "error")
            failed = True
        if flag == 1:
            if 'admin' not in request.form or request.form['admin']=='':
                flash('Права не заданы', "error")
                failed = True
        if failed:
            return render_template("/users/create.html")
        if flag == 1:
            result = do_create_user( request.form['l_name'],request.form['password'],request.form['admin'],request.cookies)
        else:
            result = do_create_user(request.form['l_name'], request.form['password'], 'False',
                                    request.cookies)
        if result.success:
            if result.response.status_code == 201:
                flash('Пользователь успешно создан', "info")
                if not g.logged_in:
                    return redirect(url_for('users.login'))
                response = redirect('/users/create')
                return response
            else:
                st = result.response.content.decode('utf-8')
                if st=='':
                    st = str(result.response.content)
                flash(st, "error")
                if not g.logged_in:
                    return redirect(url_for('users.login'))
                return redirect(url_for('users/'))
        else:
            flash(result.error)
            return redirect(url_for('users/'), "error")

gui/templates/users/create.html
{% extends "layout.html" %}
{% block title %}Добавить механика{% endblock %}
{% block body %}
  <form action="" method=post>
    <p>
      <input type=text placeholder="Имя" name=l_name value="{{ request.form.l_name }}">
    <p>
      <input type=text placeholder="Пароль" name=password value="{{ request.form.password }}">
    {% if flag == 1 %}
       <p>
       <input type=text placeholder="Права" name=admin value="{{ request.form.admin }}">
    {% endif %}
    <p>
      <input type=submit value=Ok>
    <p>

  </form>
{% endblock %}

gui/templates/users/get.html
{% extends "layout.html" %}
{% block title %}Информация о пользователе{% endblock %}
{% block body %}
    <form action="" method="get">
            <table>
            <tr>
                <th> Идентификатор пользователя </th>
                <td> {{ user["user_id"] }}</td>
            </tr>
            <tr>
                <th> Имя пользователя </th>
                <td> {{ user["l_name"] }}</td>
            </tr>
            <tr>
                <th> Admin</th>
                <td> {{ user["admin"] }}</td>
            </tr>
            <tr>
                <th> Статус машины (на починке/нет)</th>
                <td> {{ user["status"] }}</td>
            </tr>
            </table>
    </form>
{% endblock %}

gui/templates/users/get1.html
{% extends "layout.html" %}
{% block title %}Информация о пользователе{% endblock %}
{% block body %}
    <form action="" method="get">
            <table>
            <tr>
                <th> Идентификатор пользователя </th>
                <td> {{ user["user_id"] }}</td>
            </tr>
            <tr>
                <th> Имя пользователя </th>
                <td> {{ user["l_name"] }}</td>
            </tr>
            <tr>
                <th> Admin</th>
                <td> {{ user["admin"] }}</td>
            </tr>
            <tr>
                <th> Статус машины (на починке/нет)</th>
                <td> {{ user["status"] }}</td>
            </tr>
            </table>
            {% if flag=='0' %}
            <a href="{{ url_for('cars.add') }}"> (нажмите, чтобы сдать машину)</a>
            {% endif %}
    </form>
{% endblock %}

gui/templates/users/get_all.html
{% extends "layout.html" %}
{% block title %}Информация о пользователях{% endblock %}
{% block body %}
    <form action="" method="get">
            {% for item in users %}
                <table>
                <tr>
                    <th> Идентификатор пользователя </th>
                    <td> {{ item["user_id"] }}</td>
                </tr>
                <tr>
                    <th> Имя пользователя </th>
                    <td> {{ item["l_name"] }}</td>
                </tr>

                </table>
                <a href="{{ url_for('users.get', user_id=item["user_id"]) }}">Выбрать пользователя</a>
            {% endfor %}
            <p></p>
            {% if prev_url %}
                <a href="{{ url_for('tickets.get_all', page=prev_page) }}">Предыдущие пользователи</a>
            {% endif %}
            {% if next_url %}
                <a href="{{ url_for('tickets.get_all', page=next_page) }}" >Следующие пользователи</a>
            {% endif %}
    </form>
{% endblock %}

gui/templates/users/index.html
{% extends "layout.html" %}
{% block body %}
<title>{% block title %}Пользователи{% endblock %}</title>
    <p class=nav>
    <a href="{{ url_for('users.get1') }}">Профиль пользователя</a>
    <p class=nav>
    <a href="{{ url_for('users.get_all') }}">Посмотреть список всех пользователей</a>
    <p class=nav>
    {% if flag == 'True' %}
    <a href="{{ url_for('users.create') }}">Создать пользователя</a>
    {% endif %}
{% endblock %}

gui/templates/users/login.html
{% extends "layout.html" %}
{% block title %}Вход{% endblock %}
{% block body %}
    <form action="" method="post">
        <p>
            <input type=text placeholder="Логин" name=l_name value="{{ request.form.l_name }}">
        </p>
        <p>
            <input type="password" placeholder="Пароль" name=password value="{{ request.form.password }}">
        </p>
        <p>
            <input type="submit" value="Войти">
            <a href="{{ url_for('users.APIlogin1') }}">Вход через API</a>
        </p>

        <p>
            <a href="{{ url_for('users.create') }}">Регистрация</a>
        </p>
    </form>
{% endblock %}